{
    'created_at': 'Thu Jul 13 01:49:22 +0000 2017',
    'id': 885315182725136384,
    'id_str': '885315182725136384',
    'text': 'RT @jmhansler: .@CNN-obtained video shows Donald Trump with associates tied to the email controversy https://t.co/YqinZ31ShG https://t.co/T…',
    'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    'truncated': False,
    'in_reply_to_status_id': None,
    'in_reply_to_status_id_str': None,
    'in_reply_to_user_id': None,
    'in_reply_to_user_id_str': None,
    'in_reply_to_screen_name': None,
    'user': {
        'id': 151226199,
        'id_str': '151226199',
        'name': 'TD',
        'screen_name': 'ObiWanKe_Toby',
        'location': 'college park',
        'url': 'https://m.facebook.com/Unsigned-361358967559155/',
        'description': '24. MOCO.avid pot smoker. pizza enthusiast. Baseball fanatic ST.LOUIS CARDINALS! Wizards skins blues IG: obiwanke_toby Snapchat: feelsumtypaway',
        'protected': False,
        'verified': False,
        'followers_count': 315,
        'friends_count': 373,
        'listed_count': 14,
        'favourites_count': 8160,
        'statuses_count': 26261,
        'created_at': 'Wed Jun 02 22:48:13 +0000 2010',
        'utc_offset': -18000,
        'time_zone': 'Central Time (US & Canada)',
        'geo_enabled': True,
        'lang': 'en',
        'contributors_enabled': False,
        'is_translator': False,
        'profile_background_color': '1A1B1F',
        'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/704451447/e506b7eaeec4d58803a801456e0e3522.png',
        'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/704451447/e506b7eaeec4d58803a801456e0e3522.png',
        'profile_background_tile': True,
        'profile_link_color': '2FC2EF',
        'profile_sidebar_border_color': 'FFFFFF',
        'profile_sidebar_fill_color': '252429',
        'profile_text_color': '666666',
        'profile_use_background_image': True,
        'profile_image_url': 'http://pbs.twimg.com/profile_images/842606042814996482/2XXO39OM_normal.jpg',
        'profile_image_url_https': 'https://pbs.twimg.com/profile_images/842606042814996482/2XXO39OM_normal.jpg',
        'profile_banner_url': 'https://pbs.twimg.com/profile_banners/151226199/1490138264',
        'default_profile': False,
        'default_profile_image': False,
        'following': None,
        'follow_request_sent': None,
        'notifications': None
    },
    'geo': None,
    'coordinates': None,
    'place': None,
    'contributors': None,
    'retweeted_status': {
        'created_at': 'Wed Jul 12 21:31:21 +0000 2017',
        'id': 885250252109991936,
        'id_str': '885250252109991936',
        'text': '.@CNN-obtained video shows Donald Trump with associates tied to the email controversy https://t.co/YqinZ31ShG https://t.co/Tkq6N9Vyjx',
        'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
        'truncated': False,
        'in_reply_to_status_id': None,
        'in_reply_to_status_id_str': None,
        'in_reply_to_user_id': None,
        'in_reply_to_user_id_str': None,
        'in_reply_to_screen_name': None,
        'user': {
            'id': 470444339,
            'id_str': '470444339',
            'name': 'Jennifer Hansler',
            'screen_name': 'jmhansler',
            'location': 'Washington, DC',
            'url': 'http://www.cnn.com/profiles/jennifer-hansler',
            'description': '@CNNpolitics producer, formerly @ABC DC, @uofr alumna, #CLE born & bred, RTs≠endorsements // Tips? jennifer.hansler@cnn.com',
            'protected': False,
            'verified': True,
            'followers_count': 1132,
            'friends_count': 2126,
            'listed_count': 31,
            'favourites_count': 121,
            'statuses_count': 2817,
            'created_at': 'Sat Jan 21 19:29:37 +0000 2012',
            'utc_offset': -14400,
            'time_zone': 'Eastern Time (US & Canada)',
            'geo_enabled': False,
            'lang': 'en',
            'contributors_enabled': False,
            'is_translator': False,
            'profile_background_color': '709397',
            'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme6/bg.gif',
            'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme6/bg.gif',
            'profile_background_tile': False,
            'profile_link_color': '517DC4',
            'profile_sidebar_border_color': '86A4A6',
            'profile_sidebar_fill_color': 'A0C5C7',
            'profile_text_color': '333333',
            'profile_use_background_image': True,
            'profile_image_url': 'http://pbs.twimg.com/profile_images/882725891390001152/ukWr_Rf2_normal.jpg',
            'profile_image_url_https': 'https://pbs.twimg.com/profile_images/882725891390001152/ukWr_Rf2_normal.jpg',
            'profile_banner_url': 'https://pbs.twimg.com/profile_banners/470444339/1441551680',
            'default_profile': False,
            'default_profile_image': False,
            'following': None,
            'follow_request_sent': None,
            'notifications': None
        },
        'geo': None,
        'coordinates': None,
        'place': None,
        'contributors': None,
        'is_quote_status': False,
        'retweet_count': 310,
        'favorite_count': 380,
        'entities': {
            'hashtags': [],
            'urls': [
                {
                    'url': 'https://t.co/YqinZ31ShG',
                    'expanded_url': 'http://cnn.it/2tfyPUq',
                    'display_url': 'cnn.it/2tfyPUq',
                    'indices': [86, 109]
                },
                {
                    'url': 'https://t.co/Tkq6N9Vyjx',
                    'expanded_url': 'http://snpy.tv/2tfKhzD',
                    'display_url': 'snpy.tv/2tfKhzD',
                    'indices': [110, 133]
                }
            ],
            'user_mentions': [
                {
                    'screen_name': 'CNN',
                    'name': 'CNN',
                    'id': 759251,
                    'id_str': '759251',
                    'indices': [1, 5]
                }
            ],
            'symbols': []
        },
        'favorited': False,
        'retweeted': False,
        'possibly_sensitive': False,
        'filter_level': 'low',
        'lang': 'en'
    },
    'is_quote_status': False,
    'retweet_count': 0,
    'favorite_count': 0,
    'entities': {
        'hashtags': [],
        'urls': [
            {
                'url': 'https://t.co/YqinZ31ShG',
                'expanded_url': 'http://cnn.it/2tfyPUq',
                'display_url': 'cnn.it/2tfyPUq',
                'indices': [101, 124]
            }
        ],
        'user_mentions': [
            {
                'screen_name': 'jmhansler',
                'name': 'Jennifer Hansler',
                'id': 470444339,
                'id_str': '470444339',
                'indices': [3, 13]
            },
            {
                'screen_name': 'CNN',
                'name': 'CNN',
                'id': 759251,
                'id_str': '759251',
                'indices': [16, 20]
            }
        ],
        'symbols': []
    },
    'favorited': False,
    'retweeted': False,
    'possibly_sensitive': False,
    'filter_level': 'low',
    'lang': 'en',
    'timestamp_ms': '1499910562579'
}
